import { Geist, Geist_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next"
import CursorLightEffect from "@/Pages/CursorEffect/CursorEffect";
import "./globals.css";
import { Inter } from 'next/font/google'
import ReduxProvider from "@/components/Redux/Provider";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Home/Footer";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       
      <body
        className={`${inter.className} ${geistSans.variable} ${geistMono.variable}  custom_scrollbar font-inter`}
      >
        <ReduxProvider>
           <Analytics/>
          <CursorLightEffect />
          <Navbar />
          {children}
          <ToastContainer/>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
